# FastAPI App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-app
          image: book-apis:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "8000"
            - name: DATABASE_URL
              value: "your_database_url_here"
          ports:
            - containerPort: 8000

---
# FastAPI Service
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001

---
# Inventory Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: inventory:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "8001"
            - name: INVENTORY_DATABASE_URL
              value: "your_inventory_database_url_here"
          ports:
            - containerPort: 8001

---
# Inventory Service
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8001
      nodePort: 30002
